run_mode: kSim
trigger_mode: kManual
#trigger_mode: kAuto
robot_type: kGround
output_type: kAction
#output_type: kTopic
init_motion_enable: false
planner_trigger_lead_time: 0.0
#planner_trigger_lead_time: 0.2
smooth_heading_enable: true
init_motion:
  z_takeoff: 2.5
  z_drop: 1.7
  x_forward: 1.0

# Group related parameters to be shared between nodes.
RobotDynamics:
  v_max: 1.0
  v_init_max: 0.3
  v_homing_max: 0.3
  yaw_rate_max: 1.5
  dt: 0.05
