#!/bin/bash
set -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "${script_dir}"

images="rpz_planning rpz_gbplanner"
if [[ $# -gt 0 ]]; then
  images="$*"
fi

for f in $images; do
  echo "Building image $f"
  sudo rm -f "$f.simg"
  sudo singularity build "$f.simg" "$f.txt"
  sudo chown $USER:$USER "$f.simg"
  chmod g+rw,o=r "$f.simg"
done
