#!/bin/bash
set -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "${script_dir}"

images="rpz_planning rpz_gbplanner"
if [[ $# -gt 0 ]]; then
  images="$*"
fi

for f in $images; do
  echo "Building image ${f}..."
  rm -f "${f}.simg"
  singularity build --fakeroot "${f}.simg" "${f}.txt"
done
