run_mode: kSim
trigger_mode: kAuto
#trigger_mode: kManual
robot_type: kGround
#output_type: kAction
output_type: kTopic
init_motion_enable: true
#planner_trigger_lead_time: 0.0
planner_trigger_lead_time: 0.8
smooth_heading_enable: true
init_motion:
  z_takeoff: 2.5
  z_drop: 1.7
  x_forward: 2.5

# Group related parameters to be shared between nodes.
RobotDynamics:
  v_max: 0.8
  v_init_max: 0.3
  v_homing_max: 0.5
  yaw_rate_max: 0.5
  dt: 0.05
